sprint1
ClevertecFrontendLab/sprint1-Krautsou-Andrei pull request #1
Opened 2023-01-28 07:51 UTC by Krautsou-Andrei

2023-01-28 07:53 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1674892435/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1674892435/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1674892435/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1674892435/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1674892435/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1674892435/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1674892435/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1674892435/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1674892435/content-window.png)

2023-01-28 08:19 UTC, klichkovskiy requested changes

2023-01-28 08:19 UTC, klichkovskiy commented on src/index.js
> +            <Route path='/' element={<Contented />} />
Не должно быть столько роутов. В данном случае данные названия жанров должны быть параметрами роута (меняться в зависимости от жанра, и передавать в контентную часть отфильтрованные данные)

2023-01-28 08:19 UTC, klichkovskiy commented on src/pages/components/book/book.jsx
> +export const Book = ({ props }) => (
Что-то с картинками. Переделать!
![image](https://user-images.githubusercontent.com/62481116/215254621-de5a3bd9-4ca2-43f2-a391-ade7efae47ce.png)

2023-01-28 08:19 UTC, klichkovskiy commented on src/pages/components/book/book.jsx
> +  <div className='book' data-test-id='card'>
Также при клике на карточку отсутствует переход на страницу книги. Карточка должна быть Link

2023-01-28 08:19 UTC, klichkovskiy commented on src/pages/components/navigation/navigation.jsx
> +          <div className='navigation-view__button'>
![image](https://user-images.githubusercontent.com/62481116/215254695-a19dc01d-382c-406d-9338-5d6a9e290c08.png)
Стили должны быть как в макете!

2023-01-28 08:19 UTC, klichkovskiy commented on src/pages/components/book/book.jsx
> +        <button className='button button--book' type='button'>
![image](https://user-images.githubusercontent.com/62481116/215254726-ea00174d-7475-4333-bd6b-24e5570ed6ef.png)
Кнопку стилизуй как в макете

2023-01-28 08:19 UTC, klichkovskiy commented on src/pages/components/menu/menu.jsx
> +            <Link to='/contented' className='tab-menu__link' href='' aria-expanded='true'>
![image](https://user-images.githubusercontent.com/62481116/215254750-2604d2c2-b31a-4ab7-8a1f-8ac7f60c90f9.png)
Также должна быть активной

2023-01-28 08:19 UTC, klichkovskiy commented on src/books.json
> +[
Все константы хранятся в файле с константами!

2023-01-28 08:19 UTC, klichkovskiy commented on src/pages/components/navigation/navigation.jsx
> +  console.log(isPressButtonList);
Никаких консолей после себя не оставляй!

2023-01-28 08:19 UTC, klichkovskiy commented on src/index.js
> +import { HashRouter, Route, Routes, Navigate, BrowserRouter } from 'react-router-dom';
А зачем экспортировать то чем не пользуешься?

2023-01-28 08:19 UTC, klichkovskiy commented on src/pages/components/footer/footer.jsx
> +              <a className='social__link' href=''>
В React же есть Link, зачем a?

2023-01-28 08:19 UTC, klichkovskiy commented on src/pages/components/header/header.jsx
> +  <section className='main-page'>
А зачем двумя разными типами стилизации пользоваться? Представь если кому-то после тебя нужно что-то доделать? Это лишнее время разработки!

2023-01-28 08:19 UTC, klichkovskiy commented on src/pages/components/header/header.module.css
> +    padding-left: calc(16px + 149 * (100vw - 320px) / 1120);
Зачем такая высшая математика для padding?)))

2023-01-28 08:19 UTC, klichkovskiy commented on src/pages/components/header/header.module.css
> +  flex: 25.7%;
Что-то интересная у тебя размерность))) (можно не исправлять)

2023-01-28 08:19 UTC, klichkovskiy commented on src/pages/components/menu/menu.jsx
> +          </li>
Это же все можно промапать!

2023-01-28 08:19 UTC, klichkovskiy commented on src/pages/components/menu/menu.jsx
> +        <h2 className='tab-menu__title title--xl'>
Зачем это делать заголовками? Это же просто текст.

2023-01-28 08:19 UTC, klichkovskiy commented on src/pages/components/navigation/navigation.jsx
> +  function clickButtonTiles() {
Не работает переход на другой вид. Посмотри по своим скринам.

2023-01-28 08:19 UTC, klichkovskiy commented on src/pages/components/offer/offer.jsx
> +          <h3 className={classNames(style['item-offer__title'], style['title--lg'])}>
Просто текст. И так далее по всему коду. h1, h2 достаточно. все остальное излишне.

2023-01-28 08:19 UTC, klichkovskiy commented on src/pages/components/regulations/regulations.jsx
> +    <h2 className='regulations__title title--xxl'>Правила пользования</h2>
Это же практически одинаковые страницы, за исключением Заголовка. Зачем их два раза делать?

2023-01-28 08:32 UTC, Krautsou-Andrei commented on src/index.js
> +            <Route path='/' element={<Contented />} />
Возможно мы смортели одо и тоже видео в ютуб. Но это чистое совпадение)
https://www.youtube.com/watch?v=ApftxkYnXdo&list=PLiZoB8JBsdznY1XwBcBhHL9L7S_shPGVE&index=2

2023-01-28 08:37 UTC, Krautsou-Andrei commented on src/pages/components/book/book.jsx
> +  <div className='book' data-test-id='card'>
Я делал ссылку псевдоэлементом от заголовка. Нужно обернуть картинку в ссылку?

2023-01-29 15:58 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1675007892/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1675007892/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1675007892/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1675007892/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1675007892/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1675007892/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1675007892/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1675007892/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1675007892/content-window.png)

2023-01-29 16:19 UTC, klichkovskiy requested changes

2023-01-29 16:19 UTC, klichkovskiy commented on src/pages/components/book/book.jsx
> +          <button className='button button--book' type='button' onClick={buttonHundler}>
![image](https://user-images.githubusercontent.com/62481116/215339488-fd4ac202-5a67-4a36-a69b-9f45cc5156ac.png)
стиль кнопки не соответствует макету

2023-01-29 16:19 UTC, klichkovskiy commented on src/pages/components/book/book.jsx
> +            <svg width='20' height='19' viewBox='0 0 20 19' fill='none' xmlns='http://www.w3.org/2000/svg'>
Свг должно просто импортироваться как картинка. Это плохая практика вставлять свг в html код

2023-01-29 16:19 UTC, klichkovskiy commented on src/pages/components/book/book.jsx
> +export const Book = ({ props }) => {
![image](https://user-images.githubusercontent.com/62481116/215339562-40254150-fa43-46e6-8384-826a39a4799c.png)
Где еще часть данных?

2023-01-29 16:19 UTC, klichkovskiy commented on src/pages/components/book/book.jsx
> +export const Book = ({ props }) => {
А это что здесь делает?
![image](https://user-images.githubusercontent.com/62481116/215339587-8ec73913-553b-4967-8534-49656bfda78c.png)

2023-01-29 16:19 UTC, klichkovskiy commented on src/pages/components/book/book.jsx
> +export const Book = ({ props }) => {
Ты смотрел свое приложение перед отправкой?
![image](https://user-images.githubusercontent.com/62481116/215339621-c7b7559b-b646-4d62-b08b-3657401864ba.png)

2023-01-29 16:19 UTC, klichkovskiy commented on src/pages/main/main-page.jsx
>  export const MainPage = () => {
![image](https://user-images.githubusercontent.com/62481116/215339650-dab29028-959a-4605-b38d-a3bab662f541.png)
Где значок?

2023-01-29 16:19 UTC, klichkovskiy commented on src/pages/main/main-page.jsx
>  export const MainPage = () => {
Стили кнопок везде пересмотреть
![image](https://user-images.githubusercontent.com/62481116/215339676-6b20260a-dda0-42a0-921e-ccaa5b1ad360.png)

2023-02-01 11:19 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1675250340/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1675250340/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1675250340/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1675250340/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1675250340/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1675250340/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1675250340/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1675250340/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1675250340/content-window.png)

2023-02-01 11:22 UTC, klichkovskiy approved these changes

2023-02-01 11:24 UTC, merged